# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Gray
email: email@email.com
description: >- # this means to ignore newlines until "baseurl:"
  Lorem Ipsum
url: "https://brunofolle.com.br" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
theme: gray
permalink: /:title/
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude: [
  'Gemfile', 
  'Gemfile.lock', 
  'node_modules', 
  'Gemfile',
  'gray.gemspec',
  'Gulpfife.js', 
  'package.json',
  'package-lock.json',
  'LICENSE.txt',
  'README.md',
  'yarn.lock',
  '.gitignore'
]

#number posts for paginate
paginate: 20
paginate_path: /page/:num
locale: EN

#new variables:

#social newtworks
facebookurl: ''
twitterurl: ''
youtubeurl: ''
stackoverflowurl: ''
githuburl: ''
instagramurl: ''

#for analitycs
idanalitycs: ''

#language site
language: ''

#google verification
googleverify: ''

#email formspree
emailform: email@email.com

#disqus 
disqus_user: 

#about-me
aboutme: Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur, odit? Quibusdam atque laudantium debitis, officia esse nobis dolor, dolorem error eum, eos ea. Illum quae recusandae deserunt quo, minus ex!
aboutmeimg: https://www.placecage.com/150/150